## 00. Pytorch FUndamentals


In [ ]:
import torch
import pandas as nd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


## Introduction to Tensor

### Creating tensor

In [ ]:
# scalar

scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.item()

7

In [ ]:
# Vector

vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# MATRIX
MATRIX = torch.tensor([[7,8], [9,19]])

MATRIX

tensor([[ 7,  8],
        [ 9, 19]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[1]

tensor([ 9, 19])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# TENSOR

TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])

TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Random tensors

Why random tensors?



In [ ]:
# Create a randomtensors of size(3,4)

random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.8171, 0.5928, 0.8595, 0.2319],
        [0.6413, 0.3438, 0.2994, 0.1091],
        [0.1628, 0.3124, 0.2665, 0.0498]])

### Zeros and Ones

In [ ]:
# Creat a tensor of all zeros

zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# Creat a tensor of all ones

ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

###Create a range of tensors and tensors-like

In [ ]:
one_to_ten = torch.arange(start=1, end=10)
one_to_ten

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor data type

**Note:** 3 big error in deep learning
1. not right data type
2. not right shape
3. not right device

In [ ]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None)
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor.dtype

torch.float16

## Tensor Manipulating

In [ ]:
# Addition
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
# Multiply
tensor = torch.tensor([1,2,3])
tensor * 10

tensor([10, 20, 30])

In [ ]:
# Subtract
tensor = torch.tensor([1,2,3])
tensor - 10

tensor([-9, -8, -7])

In [ ]:
# Matrix multipication
%%time
torch.matmul(tensor, tensor)

CPU times: user 828 µs, sys: 0 ns, total: 828 µs
Wall time: 567 µs


tensor(14)

### Shapes for matrix multipication

In [ ]:
tensor_a = torch.tensor([[1,2],
                        [3,4],
                        [5,6]])

tensor_b = torch.tensor([[7,10],
                        [8,11],
                        [9,12]])


In [ ]:
## to fix tensor shape issue

tensor_b = tensor_b.T
torch.mm(tensor_a, tensor_b)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])